# Generated by Django 4.2.15 on 2024-08-22 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.contest'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='edit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.edit'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evaluator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.evaluator'),
        ),
        migrations.AddField(
            model_name='edit',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.article'),
        ),
        migrations.AddField(
            model_name='edit',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.contest'),
        ),
        migrations.AddField(
            model_name='edit',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.participant'),
        ),
        migrations.AddField(
            model_name='contest',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.group'),
        ),
        migrations.AddField(
            model_name='article',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.contest'),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('contest', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='evaluator',
            unique_together={('user', 'contest')},
        ),
        migrations.AlterUniqueTogether(
            name='edit',
            unique_together={('contest', 'diff')},
        ),
    ]
