# Generated by Django 5.1 on 2024-09-01 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0001_initial'),
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluator',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='credentials.profile'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evaluator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.evaluator'),
        ),
        migrations.AddField(
            model_name='group',
            name='manager',
            field=models.ManyToManyField(to='credentials.profile'),
        ),
        migrations.AddField(
            model_name='contest',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.group'),
        ),
        migrations.AddField(
            model_name='participant',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.contest'),
        ),
        migrations.AddField(
            model_name='edit',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.participant'),
        ),
        migrations.AddField(
            model_name='participantenrollment',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.contest'),
        ),
        migrations.AddField(
            model_name='participantenrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.participant'),
        ),
        migrations.AddField(
            model_name='participant',
            name='last_enrollment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.participantenrollment'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.contest'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='diff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.edit'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='evaluator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.evaluator'),
        ),
        migrations.AddField(
            model_name='edit',
            name='last_qualification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.qualification'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluator',
            unique_together={('profile', 'contest')},
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('contest', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='edit',
            unique_together={('contest', 'diff')},
        ),
    ]
