# Generated by Django 5.1 on 2024-10-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('contest', 'articleID')},
        ),
    ]
