# Generated by Django 5.1 on 2024-08-23 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_rename_edit_evaluation_diff_edit_last_evaluation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='last_enrollment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.participantenrollment'),
        ),
    ]
