# Generated by Django 4.2.11 on 2026-09-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_T425998'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit',
            name='diff',
            field=models.BigIntegerField(),
        ),
    ]