# Generated by Django 5.1 on 2024-08-29 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_participant_last_enrollment'),
        ('credentials', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='credentials.profile'),
        ),
    ]
