# Generated by Django 5.1 on 2024-08-29 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_alter_evaluator_user'),
        ('credentials', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluator',
            old_name='user',
            new_name='profile',
        ),
        migrations.AlterUniqueTogether(
            name='evaluator',
            unique_together={('profile', 'contest')},
        ),
    ]
