# Generated by Django 5.1 on 2024-08-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0006_rename_user_evaluator_profile_and_more'),
        ('credentials', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='manager',
            field=models.ManyToManyField(to='credentials.profile'),
        ),
    ]
