# Generated by Django 5.1 on 2024-09-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0008_alter_contest_outreach_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='global_id',
            field=models.IntegerField(blank=True),
        ),
    ]
