# Generated by Django 5.1 on 2024-09-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0009_alter_participant_global_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='attached',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='global_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='local_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
